from .animation import *
from .boxconnection import *
from .constants import IEEE_COLUMN_WIDTH, IEEE_DOUBLE_COLUMN_WIDTH
from .dimensions import (
    DimensionsGrid,
    DimensionsSingle,
    DimensionsSingleBesidesGrid,
    FloatShape,
    IntShape,
    Margins,
    Spacing,
)
from .plotlib import (
    MPLFigure,
    box_fit_tick_labels,
    flip_xlims,
    flip_ylims,
    interpret_width_height_aspect,
    mm_formatter_ax,
    mmplot,
    remove_axes,
    remove_internal_labels,
    remove_internal_last_ticks_grid,
    remove_internal_ticks,
    remove_internal_ticks_labels,
    remove_internal_titles,
    remove_ticks,
    remove_ticks_labels,
    um_formatter_ax,
)
from .quicksfigs import quickfig_grid, quickfig_single, quickfig_single_besides_grid
from .ruler import add_ruler
from .styles import (
    ALLOWED_STYLES,
    STYLE_DARK,
    STYLE_LIGHT,
    STYLE_NAMES,
    STYLE_PAPER,
    STYLE_PAPER_DARK,
    STYLE_POSTER,
    use_style,
)

__all__ = [
    "ALLOWED_STYLES",
    "IEEE_COLUMN_WIDTH",
    "IEEE_DOUBLE_COLUMN_WIDTH",
    "STYLE_DARK",
    "STYLE_LIGHT",
    "STYLE_NAMES",
    "STYLE_PAPER",
    "STYLE_PAPER_DARK",
    "STYLE_POSTER",
    "DimensionsGrid",
    "DimensionsSingle",
    "DimensionsSingleBesidesGrid",
    "FloatShape",
    "IntShape",
    "MPLFigure",
    "Margins",
    "Spacing",
    "add_ruler",
    "box_fit_tick_labels",
    "flip_xlims",
    "flip_ylims",
    "interpret_width_height_aspect",
    "mm_formatter_ax",
    "mmplot",
    "quickfig_grid",
    "quickfig_single",
    "quickfig_single_besides_grid",
    "remove_axes",
    "remove_internal_labels",
    "remove_internal_last_ticks_grid",
    "remove_internal_ticks",
    "remove_internal_ticks_labels",
    "remove_internal_titles",
    "remove_ticks",
    "remove_ticks_labels",
    "um_formatter_ax",
    "use_style",
]
