IEEE_COLUMN_WIDTH = 3.5
IEEE_DOUBLE_COLUMN_WIDTH = 7.16

STYLE_LIGHT = 0
STYLE_DARK = 1
STYLE_PAPER = 2
STYLE_POSTER = 3
STYLE_PAPER_DARK = 4


ALLOWED_STYLES = [STYLE_LIGHT, STYLE_DARK, STYLE_PAPER, STYLE_POSTER, STYLE_PAPER_DARK]
STYLE_NAMES = ["light", "dark", "paper", "poster", "paper_dark"]
